defaults:

    -
        scope:
            path: ""
        values:
            # Enables the 'Edit this page on GitHub' appearances on pages
            github_link: false
            # Enables the 'Give us feedback' appearances on pages
            feedback_link: false
