name: Pages Deploy
# description: Deploy Magento Developer Documentation with GitHub Pages

on:
    push:
        branches: [ "magento/devdocs" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout magento/devdocs
                uses: actions/checkout@v3
                with:
                    ref: magento/devdocs
            -
                name: Checkout main
                uses: actions/checkout@v3
                with:
                    ref: main
                    path: main

            -
                name: Build with Jekyll
                run: |
                    ls -l main/
                    cp -r main/. ./
                    ls -l ./
