name: Upstream Sync
# description: Merge master branch of magento/devdocs into magento/devdocs branch

on:
    schedule:
        # scheduled at 07:00 every Monday and Thursday
        -
            cron: '0 7 * * 1,4'

    workflow_dispatch:

jobs:
    fork_upstream_sync:
        runs-on: ubuntu-latest
        name: Sync latest changes from magento/devdocs

        steps:
            -
                name: Checkout fork repository
                uses: actions/checkout@v3
                with:
                    ref: magento/devdocs
            -
                name: Merge master branch of magento/devdocs into magento/devdocs branch
                id: sync
                uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
                with:
                    target_sync_branch: magento/devdocs
                    target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                    upstream_sync_branch: master
                    upstream_sync_repo: magento/devdocs

                    # Set test_mode true to run tests instead of the true action!!
                    test_mode: true
